### ISSUE TITLE
package.json contents printed to stdout

### ISSUE THREAD

**Issue by mohanraj-r** [hectotruj/vertioner#1]
Thanks for this helpful utility 👍  
I have been looking for something like this.

I run it with `yarn lerna exec --since master "vertioner"` and it works well. 
I have 2 suggestions based on the output:
1. The contents of the parsed `package.json` files are printed to stdout which makes it harder to consume the output esp in a monorepo with `lerna exec`. It would be helpful to suppress this output.
2. `Current version is the same as master. Please update your version.` is helpful message. But it would be more helpful especially in a monorepo if it includes the package name too (from package.json) e.g. `Current version of package "foo" is the same as master. Please update your version.` . Otherwise with `lerna exec` I see e.g. 
```
Current version is the same as master. Please update your version.
Current version is the same as master. Please update your version.
Current version is the same as master. Please update your version.
```

Thanks again for this util.

**Comment by hectotruj** [comment]
Thanks for the feedback! I’ll take a look at improving it 😊

**Comment by hectotruj** [comment]
Hope that helps. Changes should now look like this:

```sh
Package 'vertioner' has diverged from master
Current version 1.0.5, master version: 1.0.4
```

and

```sh
Package 'vertioner' has diverged from master
Current version of package 'vertioner' is the same as master. Please update your version.
```


Please let me know if there is anything else I can help with!

**Comment by mohanraj-r** [comment]
Thanks very much @hectotruj 👍

**Comment by mohanraj-r** [comment]
Please let me know once you have published to npm so I can upgrade and try it out.

**Comment by mohanraj-r** [comment]
@hectotruj Can you please publish the latest version to npm

**Comment by hectotruj** [comment]
Should be there now. I'll work on some auto-deployment soon so this doesnt happen again. Thank you!
